Add error messages
dave-msk/broker pull request #2
Opened 2019-02-27 10:43 UTC by jqli0201

2019-02-27 15:06 UTC, dave-msk requested changes

2019-02-27 15:06 UTC, dave-msk commented on afb/utils/errors.py
> +                                "Given: {}".format(type_spec))
`type_spec` is the required structure, while `struct` is the input structure being validated. As user would need to know what goes wrong when this error is raised, it would be best to provide both pieces of information in the message.

As this error corresponds to the length mismatch between the expected and given tuple, it would be best if the length information is also provided for the user to spot the problem quickly.

The required structure refers to the **type specification**, whose detailed description will be included in the documentation. It would be nice to mention it here to have the user look it up in the docs.

2019-02-27 15:06 UTC, dave-msk commented on afb/utils/errors.py
> +    raise TypeError("The expected type must be either of the following:\n"
I guess what you wanted to say is probably that the **input** itself should be one of the items in the listed ones, but not the **expected type**

2019-02-27 15:06 UTC, dave-msk commented on afb/utils/errors.py
> +                    "1. Null; \n"
`Null` should probably be `None` as this is a Python library.

2019-02-27 15:06 UTC, dave-msk commented on afb/utils/errors.py
> +                    "3. An object of `struct`")
In fact, this point refers to the **object specification**, which is a singleton `dict` with the key referring to the factory of the expected type, and the value being a `dict` that contains its arguments.
The concept of **object specification** should probably be introduced in detail in the documentation, it would be best to just give a brief description of what it looks like here

And, again, it would be more informative if the expected type and the given input are shown in the error message to help users to speed up debugging

2019-02-27 15:06 UTC, dave-msk commented on afb/utils/errors.py
> +                                "Given: {}".format(type_spec))
See comment on line 104

2019-03-08 08:28 UTC, jqli0201 commented
Thank you for help @dave-msk , please review again.

2019-03-08 13:00 UTC, dave-msk approved these changes
LGTM. Thank you for the contribution!

2019-03-08 13:00 UTC, merged

2019-03-08 13:00 UTC, dave-msk commented
Merged